name: Automated Data Pipeline

on:
  schedule:
    # Runs at 9 AM and 8 PM UTC every day
    - cron: '0 9,20 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          tesseract-ocr \
          libtesseract-dev \
          python3-dev \
          python3-pip \
          python3-venv \
          xvfb \
          libgtk-3-0 \
          libnotify-dev \
          libgconf-2-4 \
          libnss3 \
          libxss1 \
          libasound2 \
          libxtst6
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install \
          playwright \
          pandas \
          openpyxl \
          gspread \
          pytesseract \
          pillow \
          python-dateutil \
          requests \
          oauth2client
        playwright install
        playwright install-deps
        
    - name: Run main pipeline script
      run: |
        xvfb-run python master_script.py
      env:
        DISPLAY: ':99'
