name: BookMyShow Event Scraper

on:
  schedule:
    - cron: '0 9,20 * * *'
  workflow_dispatch:

permissions:
  contents: write # Needed for committing and pushing changes

jobs:
  scrape-and-process:
    runs-on: ubuntu-latest
    
    steps:
    # --- Setup ---
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true # Good for pushing changes

    # --- Environment ---
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Ensure this matches your local Python version if specific packages are compiled

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium
        playwright install-deps
        # Install jq for JSON validation in the debug step
        sudo apt-get update && sudo apt-get install -y jq

    # --- Scraping Pipeline ---
    - name: Run URL fetcher
      run: python 01_url_fetcher.py

    - name: Run screenshot capture
      run: python 02_url_to_ss.py

    - name: Run OCR processing
      run: python 03_ss_to_json.py

    - name: Convert to Excel
      run: python 04_json_to_excel.py

    # --- Google Sheets Upload ---
    - name: Create service_account.json from secret # This is the corrected step
      env:
        # **IMPORTANT:** This secret name MUST exactly match the name in your GitHub repo settings.
        # It's 'GOOGLE_SERVICE_ACCOUNT' as per your provided workflow.
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }} 
      run: |
        echo "--- Current Working Directory ---"
        pwd
        echo "--- Files in Current Directory BEFORE creation ---"
        ls -la
        
        echo "--- Attempting to create service_account.json ---"
        # THIS IS THE CRITICAL FIX: Ensure this line correctly echoes the environment variable content.
        echo "${{ env.GOOGLE_SERVICE_ACCOUNT_KEY }}" > service_account.json
        
        echo "--- Files in Current Directory AFTER creation ---"
        ls -la
        
        # --- DEBUGGING LINES (UNCOMMENT ONLY IF YOU NEED TO INSPECT THE SECRET IN LOGS) ---
        # echo "--- Content of service_account.json (first few lines) ---"
        # head service_account.json
        # echo "--- Full content of service_account.json (for deep inspection - REMOVE AFTER DEBUGGING) ---"
        # cat service_account.json 
        # echo "--- Validating service_account.json with jq ---"
        # jq . service_account.json || { echo "ERROR: service_account.json is NOT valid JSON!"; exit 1; }
        # echo "service_account.json is valid JSON."
        # --- END DEBUGGING LINES ---

    - name: Upload to Google Sheets
      # No need for an env block here, as 05_upload_to_sheets.py reads from the created file
      run: python 05_upload_to_sheets.py

    # --- Git Operations ---
    - name: Commit changes
      id: commit # Keep the ID for conditional push
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Add all relevant output files (assuming events.xlsx is generated/modified)
        git add data/ reports/ events.xlsx 
        
        if git diff --cached --quiet; then
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "No changes to commit."
        else
          git commit -m "Auto-update: Event data [skip ci]"
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "Changes committed."
        fi

    - name: Push changes
      if: steps.commit.outputs.changes == 'true' # Only push if changes were committed
      run: |
        # Pull with rebase to get latest changes and reapply yours,
        # which is safer than just rebase followed by push.
        git pull --rebase origin main # Assuming 'main' is your default branch
        git push

    # --- Artifacts ---
    - name: Archive results
      uses: actions/upload-artifact@v4
      with:
        name: event-reports
        path: |
          reports/
          screenshots/
          events.xlsx
