name: BookMyShow Event Scraper

on:
  schedule:
    - cron: '0 8 * * *'  # 8:00 AM UTC (1:30 PM IST)
  workflow_dispatch:

jobs:
  scrape-and-process:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for proper git history
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install tesseract-ocr
        sudo apt-get install libtesseract-dev
        
    - name: Install Playwright browsers
      run: |
        python -m playwright install
        python -m playwright install-deps
        
    - name: Create necessary directories
      run: |
        mkdir -p data/bookmyshow
        mkdir -p reports
        mkdir -p screenshots
        
    - name: Run URL fetcher
      run: python 01_url_fetcher.py
      
    - name: Run screenshot capture
      run: python 02_url_to_ss.py
      
    - name: Archive screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: event-screenshots
        path: screenshots/
        
    - name: Commit reports to repository
      if: always()
      run: |
        # Configure git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Add and commit reports
        git add reports/
        git commit -m "Add event report for $(date +'%Y-%m-%d')" || echo "No changes to commit"
        
        # Push changes
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Run OCR processing
      run: python 03_ss_to_json.py
      
    - name: Convert to Excel
      run: python 04_json_to_excel.py
      
    - name: Upload to Google Sheets
      env:
        SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      run: |
        echo "$SERVICE_ACCOUNT_KEY" > service_account.json
        python 05_upload_to_sheets.py
        rm -f service_account.json
