name: BookMyShow Event Scraper

on:
  schedule:
    # Run daily at 8:00 AM UTC (1:30 PM IST)
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  scrape-and-process:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install tesseract-ocr
        sudo apt-get install libtesseract-dev
        
    - name: Install Playwright browsers
      run: |
        python -m playwright install
        python -m playwright install-deps
        
    - name: Create necessary directories
      run: |
        mkdir -p data/bookmyshow
        mkdir -p reports
        mkdir -p screenshots
        
    - name: Run URL fetcher (01_url_fetcher.py)
      run: python 01_url_fetcher.py
      
    - name: Run screenshot capture (02_url_to_ss.py)
      run: python 02_url_to_ss.py
      
    - name: Run OCR processing (03_ss_to_json.py)
      run: python 03_ss_to_json.py
      
    - name: Convert to Excel (04_json_to_excel.py)
      run: python 04_json_to_excel.py
      
    - name: Upload to Google Sheets (05_upload_to_sheets.py)
      env:
        SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      run: |
        echo "$SERVICE_ACCOUNT_KEY" > service_account.json
        python 05_upload_to_sheets.py
        
    - name: Upload screenshots as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: event-screenshots
        path: screenshots/*.png
        
    - name: Upload reports as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: event-reports
        path: reports/*.txt
