name: BookMyShow Event Scraper

on:
  schedule:
    - cron: '0 9,20 * * *'  # Runs at 9 AM and 8 PM UTC (2:30 PM and 1:30 AM IST)
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Required for pushing changes back to repo

jobs:
  scrape-and-process:
    runs-on: ubuntu-latest
    
    steps:
    # --- Repository Setup ---
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for git history operations
        persist-credentials: true  # Maintains auth for push

    # --- Python Environment ---
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright pytesseract pandas gspread openpyxl pillow jq
        playwright install chromium
        playwright install-deps

    # --- Scraping Pipeline ---
    - name: Run URL fetcher
      run: python 01_url_fetcher.py

    - name: Run screenshot capture
      run: python 02_url_to_ss.py

    - name: Run OCR processing
      run: python 03_ss_to_json.py

    - name: Convert to Excel
      run: python 04_json_to_excel.py

    # --- Google Sheets Upload ---
    - name: Upload to Google Sheets
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      run: |
        # Create and validate service account JSON
        echo "$GOOGLE_CREDENTIALS" > service_account.json
        if ! jq empty service_account.json; then
          echo " Invalid service account JSON!"
          exit 1
        fi
        python 05_upload_to_sheets.py

    # --- Git Operations ---
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/ reports/
        if git diff --quiet --cached; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update: Event data [skip ci]"
          git pull --rebase
          git push
        fi

    # --- Artifacts ---
    - name: Upload results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: event-reports
        path: |
          reports/
          screenshots/
          all_event_details.json
          events.xlsx
