name: BookMyShow Event Scraper

on:
  schedule:
    - cron: '0 9,20 * * *'  # 2:30 PM and 1:30 AM IST
  workflow_dispatch:

jobs:
  scrape-and-process:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright pytesseract pandas gspread openpyxl pillow
        playwright install chromium
        playwright install-deps

    - name: Run URL fetcher
      run: python 01_url_fetcher.py

    - name: Run screenshot capture
      run: python 02_url_to_ss.py

    - name: Run OCR processing
      run: python 03_ss_to_json.py

    - name: Convert to Excel
      run: python 04_json_to_excel.py

    - name: Upload to Google Sheets
      env:
        GOOGLE_CREDENTIALS_FILE: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}  # Maps to what Python expects
      run: |
        # Create both authentication methods
        echo "$GOOGLE_CREDENTIALS_FILE" > service_account.json
        
        # Debug output
        python -c "
        import os, json
        source = 'env var' if os.getenv('GOOGLE_CREDENTIALS_FILE') else 'file'
        print(f'Using credentials from: {source}')
        print(f'Service account: {json.load(open("service_account.json"))["client_email"]}')
        "
        
        python 05_upload_to_sheets.py

    - name: Commit changes to repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/ reports/
        git diff --quiet && git diff --staged --quiet || git commit -m "Update scraped event data [skip ci]"
        git push

    - name: Upload results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: event-reports
        path: |
          reports/
          screenshots/
          all_event_details.json
          events.xlsx
