name: BookMyShow Event Pipeline

on:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 8:00 AM UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  bms-event-pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # These settings are crucial for being able to push back changes
        persist-credentials: true
        fetch-depth: 0  # Get full history for proper diffs

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install tesseract-ocr
        pip install pytesseract playwright pandas gspread
        playwright install chromium
        playwright install-deps

    - name: Create directories
      run: |
        mkdir -p data/bookmyshow
        mkdir -p reports
        mkdir -p screenshots

    - name: Run URL Fetcher
      run: python 01_url_fetcher.py

    - name: Run Screenshot Capture
      run: python 02_url_to_ss.py

    - name: Run OCR Processing
      run: python 03_ss_to_json.py

    - name: Convert to Excel
      run: python 04_json_to_excel.py

    - name: Upload to Google Sheets
      env:
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      run: |
        echo "$GOOGLE_SERVICE_ACCOUNT_JSON" > service_account.json
        python 05_upload_to_sheets.py

    - name: Commit and push changes
      run: |
        # Configure git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Add all changed files
        git add data/bookmyshow/*.json
        git add reports/*.txt
        git add screenshots/*.png
        git add events.xlsx
        
        # Commit if there are changes
        git diff-index --quiet HEAD || git commit -m "Update generated files from workflow run [skip ci]"
        
        # Push changes
        git push

    - name: Upload Screenshots as Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: event-screenshots
        path: screenshots/*.png

    - name: Upload Report as Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: event-report
        path: reports/*.txt
