name: BookMyShow Event Scraper

on:
  schedule:
    - cron: '0 8 * * *'  # 8:00 AM UTC (1:30 PM IST)
  workflow_dispatch:

permissions:
  contents: write  # Essential for pushing commits

jobs:
  scrape-and-process:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for proper git history
        token: ${{ secrets.GITHUB_TOKEN }}  # Automatic write access
        
    # [All your existing setup steps remain the same until after screenshot capture]
    
    - name: Commit report to repository
      run: |
        # Configure git identity
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Add only the report file (not other changes)
        git add reports/event_report_$(date +'%Y-%m-%d').txt
        
        # Commit only if the report file changed
        if git diff-index --quiet HEAD --; then
          echo "No changes in today's report"
        else
          git commit -m "Add event report for $(date +'%Y-%m-%d')"
          git push origin HEAD:main
          echo "Successfully committed report"
        fi
        
    # [Rest of your workflow steps remain unchanged]
