name: BookMyShow Event Scraper

on:
  schedule:
    - cron: '0 9,20 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape-and-process:
    runs-on: ubuntu-latest
    
    steps:
    # --- Setup ---
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true

    # --- Environment ---
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium
        playwright install-deps

    # --- Scraping Pipeline ---
    - name: Run URL fetcher
      run: python 01_url_fetcher.py

    - name: Run screenshot capture
      run: python 02_url_to_ss.py

    - name: Run OCR processing
      run: python 03_ss_to_json.py

    - name: Convert to Excel
      run: python 04_json_to_excel.py

    # --- Google Sheets Upload ---
    - name: Validate service account
      run: |
        if [ ! -f "service_account.json" ]; then
          echo "$GOOGLE_CREDENTIALS" > service_account.json
          jq empty service_account.json || exit 1
        fi

    - name: Upload to Google Sheets
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      run: python 05_upload_to_sheets.py

    # --- Git Operations ---
    - name: Commit changes
      id: commit
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/ reports/
        if git diff --cached --quiet; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          git commit -m "Auto-update: Event data [skip ci]"
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Push changes
      if: steps.commit.outputs.changes == 'true'
      run: |
        git fetch
        git rebase origin/main
        git push

    # --- Artifacts ---
    - name: Archive results
      uses: actions/upload-artifact@v4
      with:
        name: event-reports
        path: |
          reports/
          screenshots/
          events.xlsx
