name: BookMyShow Event Pipeline

on:
  schedule:
    - cron: '0 8 * * *'  # Runs every day at 8:00 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  bms-event-pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install tesseract-ocr
        pip install pytesseract playwright
        playwright install chromium
        playwright install-deps

    - name: Create directories
      run: |
        mkdir -p data/bookmyshow
        mkdir -p reports
        mkdir -p screenshots

    - name: Run URL Fetcher
      run: python 01_url_fetcher.py

    - name: Run Screenshot Capture
      run: python 02_url_to_ss.py

    - name: Run OCR Processing
      run: python 03_ss_to_json.py

    - name: Convert to Excel
      run: python 04_json_to_excel.py

    - name: Upload to Google Sheets
      env:
        GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      run: python 05_upload_to_sheets.py

    - name: Upload Screenshots as Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: event-screenshots
        path: screenshots/*.png

    - name: Upload Report as Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: event-report
        path: reports/*.txt
