name: Test Service Account JSON Secret
on: [workflow_dispatch]  # Manually trigger this run

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check JSON validity
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > temp.json
          python -c "
          import json, os
          try:
            with open('temp.json') as f:
              data = json.load(f)
            print('✅ JSON is valid! Service account:', data['client_email'])
          except Exception as e:
            print('❌ Invalid JSON:', e)
          os.remove('temp.json')
          "
